# Generated by Django 4.2.2 on 2023-07-03 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LibrarySpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lib_name', models.CharField(max_length=300)),
                ('lib_date_opened', models.DateTimeField(verbose_name='date opened')),
                ('lib_address', models.CharField(max_length=400)),
                ('lib_book_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=200)),
                ('book_author', models.CharField(max_length=200)),
                ('book_pub_date', models.DateTimeField(verbose_name='date published')),
                ('book_pages', models.IntegerField(default=0)),
                ('libdeck_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libdeck.libraryspace')),
            ],
        ),
    ]
