# Generated by Django 4.2.2 on 2023-07-09 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libdeck', '0004_alter_book_book_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_pub_date',
            field=models.DateField(blank=True, verbose_name='Date published'),
        ),
    ]
